trigger:
- main  # Adjust the branch name if necessary

pool:
  vmImage: 'ubuntu-latest'  # Use 'windows-latest' or 'macos-latest' if needed

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'  # Change this based on your JDK version
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx1024m'
    sonarQubeRunAnalysis: false  # Set to true if using SonarQube

- task: CopyFiles@2
  inputs:
    contents: '**/target/*.jar'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
